<?php

namespace AppBundle\Repository;

/**
 * BuilderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BauherrRepository extends \Doctrine\ORM\EntityRepository
{
}
