<?php

namespace AppBundle\Repository;

/**
 * HausRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HausRepository extends \Doctrine\ORM\EntityRepository
{
}
