<?php

namespace AppBundle\Repository;

/**
 * RollenGroup
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RollenGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
