<?php

namespace AppBundle\Repository;

/**
 * TerminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TerminRepository extends \Doctrine\ORM\EntityRepository
{
}
